name: CI with Central AI Analyzer

on:
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    env:
      AI_API_KEY: ${{ secrets.AI_API_KEY }}
    steps:
      - name: Checkout application code
        uses: actions/checkout@v3

      - name: Clone central AI analyzer
        run: |
          git clone https://github.com/<your-username>/ai-log-analyzer.git scripts/ai-analyzer

      - name: Run build
        run: |
          chmod +x build.sh
          ./build.sh 2>&1 | tee logs/build_log.txt

      - name: Run AI analysis
        run: |
          python3 scripts/ai-analyzer/scripts/analyze_log.py logs/build_log.txt logs/analysis.txt

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🤖 AI Log Analysis:
            $(cat logs/analysis.txt)